spring.application.name=shipment_transmital_load_pdf
server.port=8083
logo.path=classpath:img/pic_for_test.jpg
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.datasource.url=jdbc:mysql://localhost:3307/user_info?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

#used to tell hibernate that how sql statements are compatible with over database in my case it's MYSQL
# also Spring boot Auto detect the dialect based on the JDBC Driver but it may be default MySQL5Dialect or generic SQL.

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect




